var checkTemp = prompt('Mis on temperatuur?')
if (checkTemp >= 0 && checkTemp <= 20)
    console.log('-1')
else if (checkTemp >= 21 && checkTemp <= 40)
    console.log('0')
else if (checkTemp >=41 && checkTemp <= 60)
    console.log('1')